# Generated by Django 5.0.7 on 2024-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='creation_date',
            field=models.DateField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(verbose_name='полное содержание'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='краткое содержание'),
        ),
    ]
