# Generated by Django 5.0.7 on 2024-07-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_category_hashtag_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
