# Generated by Django 5.0.7 on 2024-08-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_hashtag_publication_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='read_time',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='время для чтения'),
        ),
        migrations.AddField(
            model_name='publication',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в ')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.publication', verbose_name='Публикация')),
            ],
        ),
    ]
